### ISSUE TITLE
How to wire recursive folder publisning into the publish pipeline

### ISSUE THREAD

**Issue by maxslabyak** [robhabraken/sitecore-power-publish#1]
Interested in this code:
https://github.com/robhabraken/sitecore-power-publish/blob/master/robhabraken.SitecoreTools.PowerPublish/PublishingHelper.cs#L46

How would you incorporate it into the publishing pipeline for select targets and languages? Also how would you enable it to only run on items in the media library?

**Comment by robhabraken** [comment]
Then you need to hook into the publishing pipeline. However, I would be cautious / careful automating this task; it could trigger a chain of publishing actions, each firing a new recursive loop, potentially ending up publishing the whole database. That's why I did not build it like this and why I don't want to change this behaviour. I'll stick to manual triggers only.

Checking the parent item can be done by looping up on each item to see if you it the media library root by ID, but that can be an expensive operation. Better would be checking template ID of images and media library folders.
